var group___fifty_one_degrees_common =
[
    [ "Arrays", "group___fifty_one_degrees_array.html", "group___fifty_one_degrees_array" ],
    [ "Cache", "group___fifty_one_degrees_cache.html", "group___fifty_one_degrees_cache" ],
    [ "Collection", "group___fifty_one_degrees_collection.html", "group___fifty_one_degrees_collection" ],
    [ "CollectionKey", "group___fifty_one_degrees_collection_key.html", "group___fifty_one_degrees_collection_key" ],
    [ "CollectionKeyTypes", "group___fifty_one_degrees_collection_key_types.html", "group___fifty_one_degrees_collection_key_types" ],
    [ "Component", "group___fifty_one_degrees_component.html", "group___fifty_one_degrees_component" ],
    [ "Config", "group___fifty_one_degrees_config.html", "group___fifty_one_degrees_config" ],
    [ "Data", "group___fifty_one_degrees_data.html", "group___fifty_one_degrees_data" ],
    [ "Data Set", "group___fifty_one_degrees_data_set.html", "group___fifty_one_degrees_data_set" ],
    [ "Date", "group___fifty_one_degrees_date.html", "group___fifty_one_degrees_date" ],
    [ "Exceptions", "group___fifty_one_degrees_exceptions.html", "group___fifty_one_degrees_exceptions" ],
    [ "Synonyms", "group___fifty_one_degrees_synonyms.html", "group___fifty_one_degrees_synonyms" ],
    [ "File", "group___fifty_one_degrees_file.html", "group___fifty_one_degrees_file" ],
    [ "Float", "group__fiftyone_degrees_float.html", "group__fiftyone_degrees_float" ],
    [ "Headers", "group___fifty_one_degrees_headers.html", "group___fifty_one_degrees_headers" ],
    [ "Indices", "group___fifty_one_degrees_indices.html", "group___fifty_one_degrees_indices" ],
    [ "IP", "group__fiftyone_degrees_ip.html", "group__fiftyone_degrees_ip" ],
    [ "JSON", "group___fifty_one_degrees_json.html", "group___fifty_one_degrees_json" ],
    [ "List", "group___fifty_one_degrees_list.html", "group___fifty_one_degrees_list" ],
    [ "Memory", "group___fifty_one_degrees_memory.html", "group___fifty_one_degrees_memory" ],
    [ "Overrides", "group___fifty_one_degrees_overrides.html", "group___fifty_one_degrees_overrides" ],
    [ "Pool", "group___fifty_one_degrees_pool.html", "group___fifty_one_degrees_pool" ],
    [ "Profile", "group___fifty_one_degrees_profile.html", "group___fifty_one_degrees_profile" ],
    [ "Properties", "group___fifty_one_degrees_properties.html", "group___fifty_one_degrees_properties" ],
    [ "Property", "group___fifty_one_degrees_property.html", "group___fifty_one_degrees_property" ],
    [ "Resource Manager", "group___fifty_one_degrees_resource.html", "group___fifty_one_degrees_resource" ],
    [ "Results", "group___fifty_one_degrees_results.html", "group___fifty_one_degrees_results" ],
    [ "Status", "group___fifty_one_degrees_status.html", "group___fifty_one_degrees_status" ],
    [ "String", "group___fifty_one_degrees_string.html", "group___fifty_one_degrees_string" ],
    [ "TextFile", "group___fifty_one_degrees_text_file.html", "group___fifty_one_degrees_text_file" ],
    [ "Threading", "group___fifty_one_degrees_threading.html", "group___fifty_one_degrees_threading" ],
    [ "Tree", "group___fifty_one_degrees_tree.html", "group___fifty_one_degrees_tree" ],
    [ "Values", "group___fifty_one_degrees_value.html", "group___fifty_one_degrees_value" ],
    [ "fiftyoneDegreesEvidencePrefix", "group___fifty_one_degrees_common.html#ga1ff9010650f2716970e86c12c5a97a76", [
      [ "FIFTYONE_DEGREES_EVIDENCE_HTTP_HEADER_STRING", "group___fifty_one_degrees_common.html#gga1ff9010650f2716970e86c12c5a97a76a5bfdff3692f3fd3bb0506a7117e55402", null ],
      [ "FIFTYONE_DEGREES_EVIDENCE_HTTP_HEADER_IP_ADDRESSES", "group___fifty_one_degrees_common.html#gga1ff9010650f2716970e86c12c5a97a76a4422eb1064160f695cef887801bbd6e6", null ],
      [ "FIFTYONE_DEGREES_EVIDENCE_SERVER", "group___fifty_one_degrees_common.html#gga1ff9010650f2716970e86c12c5a97a76a723e89faa3168d882c6b7c70e04c0976", null ],
      [ "FIFTYONE_DEGREES_EVIDENCE_QUERY", "group___fifty_one_degrees_common.html#gga1ff9010650f2716970e86c12c5a97a76a15b343154fc012939b162c1c0495fe1c", null ],
      [ "FIFTYONE_DEGREES_EVIDENCE_COOKIE", "group___fifty_one_degrees_common.html#gga1ff9010650f2716970e86c12c5a97a76a5921c7e8306df98c603fdb32d96d4924", null ],
      [ "FIFTYONE_DEGREES_EVIDENCE_IGNORE", "group___fifty_one_degrees_common.html#gga1ff9010650f2716970e86c12c5a97a76a61b6045bdab8eb5b4aca237971e00b9d", null ]
    ] ]
];