# This is a development pipeline which run a set of confidence tests.
# Just to make sure core functions do not break.
trigger: none

# Triggered by any PRs not to one of the main branches.
pr:
  branches:
    exclude:
    - master
    - develop
    - release/*
    - hotfix/*

resources:
  repositories:
  - repository: ciTemplates # Id of the repository used to reference to in this script
    type: git
    name: common-ci # Name of the actual repository

# Include shared variables
variables:
- template: shared-variables.yml
- template: shared-variables.yml@ciTemplates
- group: CIAutomation # Required to access CI variables

stages:
# We only run smoke tests so developers can get a quick feedback.
- template: shared-build-and-test-stages.yml
  parameters:
    windowsImage: $(windowsImage)
    linuxImage: $(linuxImage)
    macImage: $(macImage)
    vsTestsToRun: $(vsSmokeTestsToRun)
    cmakeTestsToRun: $(cmakeSmokeTestsToRun)
    platformToolsetVersion: '${{ variables.plfTsVer }}'
    windowsSDKVersion: '${{ variables.winSDKVer }}'
    runTests: variables['RunTests']