# This pipeline is used for regression testing to run the full set of tests.
trigger: none

# Triggered by PRs to any of the main branches
pr:
  - master
  - develop
  - release/*
  - hotfix/*

# Schedule to run overnight
schedules:
- cron: "0 20 * * *"
  displayName: Daily overnight build
  branches:
    include:
    - develop

# Include shared variables
variables:
- template: shared-variables.yml
- group: CIAutomation # Required to access CI variables

resources:
  repositories:
  - repository: ciTemplates # Id of the repository used to reference to in this script
    type: git
    name: common-ci # Name of the actual repository

stages:
# Use full set of tests.
- template: shared-build-and-test-stages.yml
  parameters:
    windowsImage: $(windowsImage)
    linuxImage: $(linuxImage)
    macImage: $(macImage)
    vsTestsToRun: $(vsFullTestsToRun)
    cmakeTestsToRun: $(cmakeFullTestsToRun)
    runTests: variables['RunTests']
    
# Try to complete the corresponding pull request if
# this is triggered by one.    
- template: shared-auto-complete-pr-stage.yml@ciTemplates
  parameters:
    stageDependencies: [Linux,MacOS,Windows]