trigger: 
  - master
  - develop
  - release/*

# Don't trigger for a pull request
pr: none

resources:
  repositories:
    - repository: ciTemplates # Id of the repository used to reference to in this script
      type: git
      name: common-ci # Name of the actual repository

# Include shared variables
variables:
- template: shared-variables.yml@ciTemplates

stages:

- stage: Tagging

  jobs:
  - template: shared-create-tag-job.yml@ciTemplates
    parameters:
      imageName: $(linuxImage)