name: Nightly Documentation Update

on:
  workflow_dispatch:
    inputs:
      dryrun:
        default: false
        type: boolean
        description: Dry Run
  schedule:
    - cron:  '0 3 * * *'

jobs:
  NightlyDocumentationUpdate:
    uses: 51Degrees/common-ci/.github/workflows/nightly-documentation-update.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      dryrun: ${{ inputs.dryrun || false }}
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}

  NightlyDocumentationUpdate-v4_5:
    needs: NightlyDocumentationUpdate
    if: ${{ !cancelled() }}
    uses: 51Degrees/common-ci/.github/workflows/nightly-documentation-update.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      branch: version/4.5
      dryrun: ${{ inputs.dryrun || false }}
    secrets: 
      token: ${{ secrets.ACCESS_TOKEN }}
